### ISSUE TITLE
Error type 405 need more clarity

### ISSUE THREAD

**Issue by mjaggala** [tudelft3d/val3dity#101]
Val3dity reporting Error type 405, even though all surfaces are in correct orientation. 
Please find attached DGN and GML for your review.

We are unable to understand and fix this type of error. Please suggest.

![405](https://user-images.githubusercontent.com/32330491/31996510-68b11186-b9a6-11e7-930b-5355687bd7e0.JPG)

[405_Issue_Lod2.zip](https://github.com/tudelft3d/val3dity/files/1414396/405_Issue_Lod2.zip)

**Comment by balazsdukai** [comment]
I'm assuming that the error has to do with the `ClosureSurface` in the building. It does not form a closed inner shell, thus there are two faces with the same orientation "covering" each other (ClosureSurface and outer WallSurface).  But I leave it for @hugoledoux to decide.

![closure](https://user-images.githubusercontent.com/7190603/32009702-1333b0f6-b9b0-11e7-8b0f-21dc5b4e83e2.png)

![closure2](https://user-images.githubusercontent.com/7190603/32009775-4da60158-b9b0-11e7-88ec-56d44128849b.png)

**Comment by hugoledoux** [comment]
The `ClosureSurface` is not the problem here, actually there is no problem with this file. It is valid (both Solids in it are).

The bug is known: it is with one open-source library that val3dity uses. With feedback from users, I caught one bug in it and it was fixed ~6mo ago (see https://github.com/CGAL/cgal/issues/2048 and https://github.com/CGAL/cgal/pull/2057 for details).

The binary of Windows is still compiled against CGAL 4.9, but that bug was fixed in 4.10.

How do you use val3dity actually?
