### ISSUE TITLE
Error code 601 - Buildingparts_overlap

### ISSUE THREAD

**Issue by CWisse** [tudelft3d/val3dity#160]
I have a (my sincere apologies) CityGML file with a building containing LoD1 and LoD2 Geometry. There are no BuildingParts modelled. Using Val3dity I get the error code 601 Buildingparts_overlap. Is this a standard error when using LoD1 and Lod2 Geometry of a single building in a single file? 

[0599100000431693FME.gml.txt](https://github.com/tudelft3d/val3dity/files/6130661/0599100000431693FME.gml.txt)

**Comment by hugoledoux** [comment]
No need to apologise for using CityGML, if you like to make your life miserable it's up to you, huh.

Yes the reason is that all the BuildingParts for a given building, *at all LoDs*, are taken in the process (see #133). This is something that I will fix in the future, but only for CityJSON.

In meantime, just store the different LoDs in different files. In CityJSON use [cjio](https://github.com/cityjson/cjio): `cjio myfile.json extract_lod 2 save out.json` does that. In CityGML: [citygml-tools](https://github.com/citygml4j/citygml-tools) has a similar function I reckon.
