### ISSUE TITLE
online val3dity complex solid

### ISSUE THREAD

**Issue by chenkianwee** [tudelft3d/val3dity#23]
Hi, thanks for the really fast fix to the bug. But I just tried the file on the online val3dity, its still giving me the error. Is the online version not updated ?

**Comment by hugoledoux** [comment]
No, I thought you could test it too and then I update the web-app. But perhaps you haven't compiled it or don't know how?

But no problem, I just updated the web-app and added an info for the version used, also useful for the future:
https://dl.dropboxusercontent.com/s/gqchrmkqgyxoe35/2017-01-31%20at%2010.26.png

The Windows EXE is not updated either, my only colleague who uses Windows is on holidays for 2 weeks... so that will have to wait.
