### ISSUE TITLE
specify location in error 302

### ISSUE THREAD

**Issue by balazsdukai** [tudelft3d/val3dity#42]
On v2.
The file `msol3` produces the error:

```
		<Error>
			<code>302</code>
			<type>SHELL_NOT_CLOSED</type>
			<surface_id></surface_id>
			<info>Location hole: 0 0 0</info>
		</Error>
```

Describe in `docs:error` what does `Location hole: 0 0 0` refer to? What is `0 0 0`?

**Comment by hugoledoux** [comment]
yeah that's the problem with having a structure report. Here no surface can be reported since the surface is missing! But for other errors related to shells, the surface should be reported...

Maybe better to have just a field "info" where I put details about the issue? Because that arises also for CompositeSolid eg, there it's not surface but solid.

**Comment by balazsdukai** [comment]
For completeness sake from our discussion:
+ `Location hole 0 0 0` refers to the coordinates of one vertex in the polygon that represents the hole

**Comment by hugoledoux** [comment]
this has been solved
