### ISSUE TITLE
error 304 instead of 303

### ISSUE THREAD

**Issue by balazsdukai** [tudelft3d/val3dity#60]
On branch v2_test
Run `pytest -k "303" -v`. 
It reports 304 although data contains non-manifold vertices. Maybe 303 and 304 could be merged into a `NON_MANIFOLD_VERTEX_OR_EDGE` category? Similarly as in the case with #52

**Comment by hugoledoux** [comment]
this is a complex case. 

If one has a valid Solid, let's say a cube, and tries to add another face dangling, either touching at a vertex or incident to an edge, then I can't with CGAL (or don't know how) make the difference between these 2 cases, I'll just know it's non-manifold.

But if you check in /data/obj/nonmanifold.obj there's an interesting case. 
`val3dity nonmanifold.obj -p Solid` --> error 302
`val3dity nonmanifold.obj -p CompositeSurface` --> error 303 (because here the surface is valid but the umbrella is not complete...

Thus, some error 303 are reported as 304, but not all :/

I can think I should merge the two errors indeed. I need to sleep on that one, perhaps there's a solution I haven't figured out.

**Comment by balazsdukai** [comment]
Hm, just a guess, but would sth work along these lines?

1. if 303 or 304 reported
    1. get the edges that cause the problem
    2. if any of these edges share >1 (or exactly 2) vertices, then
        1. report 304
    3. else report 303

**Comment by hugoledoux** [comment]
fixed, 303 is now for both: "NON_MANIFOLD_CASE"
