### ISSUE TITLE
307 also reports 304

### ISSUE THREAD

**Issue by balazsdukai** [tudelft3d/val3dity#62]
On branch v2_test
Run `pytest -k "307" -v`
Test `307` reports 304, 307 although the unit cube does not contain *non-manifold edge*, just a face that is oriented in the opposite direction as the rest.

**Comment by hugoledoux** [comment]
these 2 errors are very similar. Non-manifold edge would mean that there are 2+ faces incident to an edge, but here if we try to insert one (wrongly oriented) face then it's not possible because there's already an edge (it's done by checking if each edge is there twice: once in each direction).

So both 304 and 307 can be reported, and usually a mix of both depending on the config. If 307 is reported this is good enough I reckon.
