### ISSUE TITLE
To validate or not to validate a schema?

### ISSUE THREAD

**Issue by balazsdukai** [tudelft3d/val3dity#74]
It appears to me that CityGML files are validated against the schema if there is anything wrong, `901 - Invalid input file` is reported. So essentially, the same schema validation is done as by the [CityGML schema validator](http://geovalidation.bk.tudelft.nl/schemacitygml/) but with a simplified error reporting. Is that correct?

If that is correct, then I think it could make sense to:
- highlight this feature in the documentation, because then val3dity is not only a 3D primitive validator, but a complete 3D city model validator (schema + geometry),
- implement the same thorough schema validation for the rest of the accepted formats as well

If there is no schema validation, then how does val3dity determine an invalid input file?

The question came up, because the test `pytest -k "invalid_json" -v` fails to return 901, but it returns 302, 303. Thus I think val3dity disregards the invalid schema and goes on to validate the geometries. The two input files for the test are the two invalid files in the [CityJSON example data](https://github.com/tudelft3d/cityjson/tree/master/example-datasets/dummy-values).

Currently the error 901 feels a bit fuzzy for me, because I don't see how would it be possible to have a clear separation between schema and geometry validation, because in order to parse a file val3dity needs to know where to look for the geometry at least, right?

**Comment by hugoledoux** [comment]
no no, it's not correct: I don,t validate against the schema at all for CityGML file! I try to parse, if it's fine then great, if not then an error of some kind can be returned. 

Decided to do so because schema validation is *very slow* for large files, and one small unimportant thing could block the validation (like a non-listed attribute for CityGML). 

You could try giving back xml as input though. But more it's not scope of val3dity... I take as input valid CityGML/CityJSON files I should write more precisely though.
